services:
  device-manager:
    build:
      context: device-manager
      dockerfile: source/webapi/Dockerfile
    ports:
      - "8080:8080"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
